export const comidas = [
	{
		nombre: "Lomito Vegano",
		img: "lomitovegano.jpg",
		desc: "Pan casero, mayonesa de aquafaba, lechuga, tomate, salsa criolla, bife de seitán, repollo saltado, queso de girasol y porcion de papas.",
		variedades: [],
		precio: 600,
		promo: 1000,
		id: 1,
		dias: ["viernes"],
	},
	{
		nombre: "Hamburguesa Vegana",
		img: "hamburguesa.jpg",
		desc: "Pan casero, mayonesa de aquafaba, lechuga, tomate, cebolla morada caramelizada, hamburguesa de garbanzos, huevo de tofu, pasta de zanahoria, y porción de papas.",
		variedades: [],
		precio: 550,
		promo: 950,
		id: 2,
		dias: ["viernes"],
	},
	{
		nombre: "Sorrentinos",
		img: "sorren.jpg",
		"sub-titulo-1": "Variedades:",
		desc: "",
		variedades: ["Jamón y Queso", "Calabacín, Nuez y Queso"],
		precio: 550,
		promo: 950,
		id: 3,
		dias: ["sabados"],
	},
	{
		nombre: "Locro",
		img: "locro.jpg",
		desc: "Cuero de chancho, porotos y zapallo, que mas queré",
		variedades: [],
		precio: 850,
		promo: 0,
		id: 4,
		dias: ["25 de mayo", "20 de junio", "9 de julio"],
	},
]
