export const foods = [
  {
    "name": "Lomito Vegano",
    "keyword": "lomo",
    "img": "lomitovegano.jpg",
    "desc": [
      "Pan casero, mayonesa de aquafaba, lechuga, tomate, salsa criolla, bife de seitán, repollo saltado, queso de girasol y porcion de papas.",
    ],
    "precio": 600,
    "promo": 1000,
    "id": 1,
    "dias": ["viernes"],
  },
  {
    "name": "Burger Vegana",
    "keyword": "hambur",
    "img": "hamburguesa.jpg",
    "desc": [
      "Pan casero, mayonesa de aquafaba, lechuga, tomate, cebolla morada caramelizada, hamburguesa de garbanzos, huevo de tofu, pasta de zanahoria, y porción de papas.",
    ],
    "precio": 550,
    "promo": 950,
    "id": 2,
    "dias": ["viernes"],
  },
  {
    "name": "Sorrentinos",
    "keyword": "sorren",
    "img": "sorren.jpg",
    "sub-titulo-1": "Variedades:",
    "desc": ["Jamón y Queso", "Calabacín, Nuez y Queso"],
    "precio": 550,
    "promo": 950,
    "id": 3,
    "dias": ["sabado"],
  },
  {
    "name": "Locro",
    "keyword": "locro",
    "img": "locro.jpg",
    "desc": [],
    "precio": 850,
    "promo": 1700,
    "id": 4,
    "dias": ["25 de mayo", "20 de junio", "9 de julio"],
  },
]
